// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_picture_display_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            type: 'integer',
            title: 'Display Duration Seconds',
            default: 3600
        },
        priority: {
            type: 'integer',
            title: 'Priority',
            default: 0
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_picture-display-upload_image'
} as const;

export const DeviceTypeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DeviceTypeCreate',
    description: 'Model for creating a new device type.'
} as const;

export const DeviceTypePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'DeviceTypePublic',
    description: 'Public API model for DeviceType.'
} as const;

export const DeviceTypeUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'DeviceTypeUpdate',
    description: 'Model for updating a device type.'
} as const;

export const DeviceTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DeviceTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DeviceTypesPublic',
    description: 'Paginated response for device types.'
} as const;

export const GlobalDeviceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            type: 'string',
            format: 'uuid',
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        }
    },
    type: 'object',
    required: ['name', 'device_type_id', 'skill_id'],
    title: 'GlobalDeviceCreate',
    description: 'Model for creating a new global device.'
} as const;

export const GlobalDevicePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            type: 'string',
            format: 'uuid',
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'device_type_id', 'skill_id', 'id', 'created_at', 'updated_at'],
    title: 'GlobalDevicePublic',
    description: 'Public API model for GlobalDevice.'
} as const;

export const GlobalDeviceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        device_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        }
    },
    type: 'object',
    title: 'GlobalDeviceUpdate',
    description: 'Model for updating a global device.'
} as const;

export const GlobalDevicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GlobalDevicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GlobalDevicesPublic',
    description: 'Paginated response for global devices.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            description: 'Health status of the application',
            default: 'ok'
        }
    },
    type: 'object',
    title: 'HealthResponse',
    description: `Health check response model.

Attributes:
    status: Current health status of the application.`
} as const;

export const ImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        storage_path: {
            type: 'string',
            title: 'Storage Path'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            type: 'integer',
            title: 'Display Duration Seconds'
        },
        priority: {
            type: 'integer',
            title: 'Priority'
        },
        original_width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Width'
        },
        original_height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Height'
        },
        last_displayed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Displayed At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'source_name', 'storage_path', 'title', 'description', 'author', 'source_url', 'tags', 'display_duration_seconds', 'priority', 'original_width', 'original_height', 'last_displayed_at', 'expires_at', 'created_at', 'updated_at'],
    title: 'ImagePublic',
    description: 'API response model for Image.'
} as const;

export const ImageUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 86400,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Duration Seconds'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        }
    },
    type: 'object',
    title: 'ImageUpdate',
    description: 'API request model for updating images.'
} as const;

export const ImagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImagesPublic',
    description: 'Paginated response for images.'
} as const;

export const ImmichSyncJobCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Unique job name'
        },
        target_device_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Device Id',
            description: 'Device this job syncs for'
        },
        strategy: {
            '$ref': '#/components/schemas/SyncStrategy',
            description: 'Selection strategy: RANDOM or SMART',
            default: 'RANDOM'
        },
        query: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Query',
            description: 'Semantic search query for SMART strategy'
        },
        count: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Count',
            description: 'Images to sync per run',
            default: 10
        },
        random_pick: {
            type: 'boolean',
            title: 'Random Pick',
            description: 'Randomly sample from smart search results',
            default: false
        },
        overfetch_multiplier: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: 'Overfetch Multiplier',
            description: 'Multiplier for overfetching when client-side filters active',
            default: 3
        },
        min_color_score: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Min Color Score',
            description: 'Minimum color compatibility score (0 to disable)',
            default: 0.5
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether job is active',
            default: true
        },
        album_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Album Ids',
            description: 'Filter by album UUIDs'
        },
        person_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Ids',
            description: 'Filter by person UUIDs'
        },
        tag_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag Ids',
            description: 'Filter by tag UUIDs'
        },
        is_favorite: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Favorite',
            description: 'Filter favorites only'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City',
            description: 'Filter by city'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'State',
            description: 'Filter by state/region'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country',
            description: 'Filter by country'
        },
        taken_after: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken After',
            description: 'Photos taken after this date'
        },
        taken_before: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken Before',
            description: 'Photos taken before this date'
        },
        rating: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating',
            description: 'Minimum rating (0-5)'
        }
    },
    type: 'object',
    required: ['name', 'target_device_id'],
    title: 'ImmichSyncJobCreate',
    description: 'API request model for creating sync jobs.'
} as const;

export const ImmichSyncJobPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Unique job name'
        },
        target_device_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Device Id',
            description: 'Device this job syncs for'
        },
        strategy: {
            '$ref': '#/components/schemas/SyncStrategy',
            description: 'Selection strategy: RANDOM or SMART',
            default: 'RANDOM'
        },
        query: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Query',
            description: 'Semantic search query for SMART strategy'
        },
        count: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Count',
            description: 'Images to sync per run',
            default: 10
        },
        random_pick: {
            type: 'boolean',
            title: 'Random Pick',
            description: 'Randomly sample from smart search results',
            default: false
        },
        overfetch_multiplier: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: 'Overfetch Multiplier',
            description: 'Multiplier for overfetching when client-side filters active',
            default: 3
        },
        min_color_score: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Min Color Score',
            description: 'Minimum color compatibility score (0 to disable)',
            default: 0.5
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether job is active',
            default: true
        },
        album_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Album Ids',
            description: 'Filter by album UUIDs'
        },
        person_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Ids',
            description: 'Filter by person UUIDs'
        },
        tag_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag Ids',
            description: 'Filter by tag UUIDs'
        },
        is_favorite: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Favorite',
            description: 'Filter favorites only'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City',
            description: 'Filter by city'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'State',
            description: 'Filter by state/region'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country',
            description: 'Filter by country'
        },
        taken_after: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken After',
            description: 'Photos taken after this date'
        },
        taken_before: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken Before',
            description: 'Photos taken before this date'
        },
        rating: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating',
            description: 'Minimum rating (0-5)'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'target_device_id', 'id', 'created_at', 'updated_at'],
    title: 'ImmichSyncJobPublic',
    description: 'API response model for sync jobs.'
} as const;

export const ImmichSyncJobUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        target_device_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Device Id'
        },
        strategy: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SyncStrategy'
                },
                {
                    type: 'null'
                }
            ]
        },
        query: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Query'
        },
        count: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 1000,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        random_pick: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Random Pick'
        },
        overfetch_multiplier: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overfetch Multiplier'
        },
        min_color_score: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Color Score'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        album_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Album Ids'
        },
        person_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Ids'
        },
        tag_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag Ids'
        },
        is_favorite: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Favorite'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        taken_after: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken After'
        },
        taken_before: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taken Before'
        },
        rating: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        }
    },
    type: 'object',
    title: 'ImmichSyncJobUpdate',
    description: `API request model for updating sync jobs.

All fields are optional to allow partial updates.`
} as const;

export const ImmichSyncJobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImmichSyncJobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImmichSyncJobsPublic',
    description: 'Paginated response for sync jobs.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PresignedUrlResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_in_seconds: {
            type: 'integer',
            title: 'Expires In Seconds'
        }
    },
    type: 'object',
    required: ['url', 'expires_in_seconds'],
    title: 'PresignedUrlResponse',
    description: 'Response model for presigned URL.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RoomCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoomCreate',
    description: 'Model for creating a new room.'
} as const;

export const RoomPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'RoomPublic',
    description: 'Public API model for Room.'
} as const;

export const RoomUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'RoomUpdate',
    description: 'Model for updating a room.'
} as const;

export const RoomsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RoomPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RoomsPublic',
    description: 'Paginated response for rooms.'
} as const;

export const SkillPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'created_at', 'updated_at'],
    title: 'SkillPublic',
    description: 'Public schema for Skill.'
} as const;

export const SkillsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SkillPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SkillsPublic',
    description: 'Paginated response for skills.'
} as const;

export const SyncStrategySchema = {
    type: 'string',
    enum: ['RANDOM', 'SMART'],
    title: 'SyncStrategy',
    description: `Strategy for selecting images from Immich.

Values are uppercase to match PostgreSQL enum labels created by SQLAlchemy.`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;