// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_picture_display_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            type: 'integer',
            title: 'Display Duration Seconds',
            default: 30
        },
        priority: {
            type: 'integer',
            title: 'Priority',
            default: 5
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_picture-display-upload_image'
} as const;

export const DeviceTypeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DeviceTypeCreate',
    description: 'Model for creating a new device type.'
} as const;

export const DeviceTypePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'DeviceTypePublic',
    description: 'Public API model for DeviceType.'
} as const;

export const DeviceTypeUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'DeviceTypeUpdate',
    description: 'Model for updating a device type.'
} as const;

export const DeviceTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DeviceTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DeviceTypesPublic',
    description: 'Paginated response for device types.'
} as const;

export const GlobalDeviceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            type: 'string',
            format: 'uuid',
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        }
    },
    type: 'object',
    required: ['name', 'device_type_id', 'skill_id'],
    title: 'GlobalDeviceCreate',
    description: 'Model for creating a new global device.'
} as const;

export const GlobalDevicePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        device_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            type: 'string',
            format: 'uuid',
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'device_type_id', 'skill_id', 'id', 'created_at', 'updated_at'],
    title: 'GlobalDevicePublic',
    description: 'Public API model for GlobalDevice.'
} as const;

export const GlobalDeviceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        device_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Type Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        skill_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skill Id'
        },
        pattern: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern'
        },
        device_attributes: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Attributes'
        }
    },
    type: 'object',
    title: 'GlobalDeviceUpdate',
    description: 'Model for updating a global device.'
} as const;

export const GlobalDevicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GlobalDevicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GlobalDevicesPublic',
    description: 'Paginated response for global devices.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PictureDisplayImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_name: {
            type: 'string',
            title: 'Source Name'
        },
        storage_path: {
            type: 'string',
            title: 'Storage Path'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            type: 'integer',
            title: 'Display Duration Seconds'
        },
        priority: {
            type: 'integer',
            title: 'Priority'
        },
        last_displayed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Displayed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'source_name', 'storage_path', 'title', 'description', 'tags', 'display_duration_seconds', 'priority', 'last_displayed_at', 'created_at', 'updated_at'],
    title: 'PictureDisplayImagePublic',
    description: 'Public API model for images.'
} as const;

export const PictureDisplayImageUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        display_duration_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 300,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Duration Seconds'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        }
    },
    type: 'object',
    title: 'PictureDisplayImageUpdate',
    description: 'Model for updating images.'
} as const;

export const PictureDisplayImagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PictureDisplayImagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PictureDisplayImagesPublic',
    description: 'Paginated response for images.'
} as const;

export const PresignedUrlResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_in_seconds: {
            type: 'integer',
            title: 'Expires In Seconds'
        }
    },
    type: 'object',
    required: ['url', 'expires_in_seconds'],
    title: 'PresignedUrlResponse',
    description: 'Response model for presigned URL.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RoomCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoomCreate',
    description: 'Model for creating a new room.'
} as const;

export const RoomPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'RoomPublic',
    description: 'Public API model for Room.'
} as const;

export const RoomUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'RoomUpdate',
    description: 'Model for updating a room.'
} as const;

export const RoomsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RoomPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RoomsPublic',
    description: 'Paginated response for rooms.'
} as const;

export const SkillPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'created_at', 'updated_at'],
    title: 'SkillPublic',
    description: 'Public schema for Skill.'
} as const;

export const SkillsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SkillPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SkillsPublic',
    description: 'Paginated response for skills.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;