// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DevicesReadDevicesData, DevicesReadDevicesResponse, DevicesCreateDeviceData, DevicesCreateDeviceResponse, DevicesReadDeviceData, DevicesReadDeviceResponse, DevicesUpdateDeviceData, DevicesUpdateDeviceResponse, DevicesDeleteDeviceData, DevicesDeleteDeviceResponse, DeviceTypesReadDeviceTypesData, DeviceTypesReadDeviceTypesResponse, DeviceTypesCreateDeviceTypeData, DeviceTypesCreateDeviceTypeResponse, DeviceTypesReadDeviceTypeData, DeviceTypesReadDeviceTypeResponse, DeviceTypesUpdateDeviceTypeData, DeviceTypesUpdateDeviceTypeResponse, DeviceTypesDeleteDeviceTypeData, DeviceTypesDeleteDeviceTypeResponse, ImmichSyncJobsReadSyncJobsData, ImmichSyncJobsReadSyncJobsResponse, ImmichSyncJobsCreateSyncJobData, ImmichSyncJobsCreateSyncJobResponse, ImmichSyncJobsReadSyncJobData, ImmichSyncJobsReadSyncJobResponse, ImmichSyncJobsUpdateSyncJobData, ImmichSyncJobsUpdateSyncJobResponse, ImmichSyncJobsDeleteSyncJobData, ImmichSyncJobsDeleteSyncJobResponse, InfrastructureHealthResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, MonitoringReadSkillsResponse, PictureDisplayUploadImageData, PictureDisplayUploadImageResponse, PictureDisplayReadImagesData, PictureDisplayReadImagesResponse, PictureDisplayReadImageData, PictureDisplayReadImageResponse, PictureDisplayUpdateImageData, PictureDisplayUpdateImageResponse, PictureDisplayDeleteImageData, PictureDisplayDeleteImageResponse, PictureDisplayGetImageUrlData, PictureDisplayGetImageUrlResponse, PrivateCreateUserData, PrivateCreateUserResponse, RoomsReadRoomsData, RoomsReadRoomsResponse, RoomsCreateRoomData, RoomsCreateRoomResponse, RoomsReadRoomData, RoomsReadRoomResponse, RoomsUpdateRoomData, RoomsUpdateRoomResponse, RoomsDeleteRoomData, RoomsDeleteRoomResponse, UsersReadUsersData, UsersReadUsersResponse, UsersReadUserMeResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersDeleteUserData, UsersDeleteUserResponse } from './types.gen';

export class DevicesService {
    /**
     * Read Devices
     * Retrieve global devices with pagination.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns GlobalDevicesPublic Successful Response
     * @throws ApiError
     */
    public static readDevices(data: DevicesReadDevicesData = {}): CancelablePromise<DevicesReadDevicesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/devices/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Device
     * Create new global device.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GlobalDevicePublic Successful Response
     * @throws ApiError
     */
    public static createDevice(data: DevicesCreateDeviceData): CancelablePromise<DevicesCreateDeviceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/devices/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Device
     * Get device by ID.
     * @param data The data for the request.
     * @param data.deviceId
     * @returns GlobalDevicePublic Successful Response
     * @throws ApiError
     */
    public static readDevice(data: DevicesReadDeviceData): CancelablePromise<DevicesReadDeviceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Device
     * Update a global device.
     * @param data The data for the request.
     * @param data.deviceId
     * @param data.requestBody
     * @returns GlobalDevicePublic Successful Response
     * @throws ApiError
     */
    public static updateDevice(data: DevicesUpdateDeviceData): CancelablePromise<DevicesUpdateDeviceResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Device
     * Delete a global device.
     * @param data The data for the request.
     * @param data.deviceId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteDevice(data: DevicesDeleteDeviceData): CancelablePromise<DevicesDeleteDeviceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DeviceTypesService {
    /**
     * Read Device Types
     * Retrieve device types with pagination.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns DeviceTypesPublic Successful Response
     * @throws ApiError
     */
    public static readDeviceTypes(data: DeviceTypesReadDeviceTypesData = {}): CancelablePromise<DeviceTypesReadDeviceTypesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/device-types/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Device Type
     * Create new device type.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DeviceTypePublic Successful Response
     * @throws ApiError
     */
    public static createDeviceType(data: DeviceTypesCreateDeviceTypeData): CancelablePromise<DeviceTypesCreateDeviceTypeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/device-types/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Device Type
     * Get device type by ID.
     * @param data The data for the request.
     * @param data.deviceTypeId
     * @returns DeviceTypePublic Successful Response
     * @throws ApiError
     */
    public static readDeviceType(data: DeviceTypesReadDeviceTypeData): CancelablePromise<DeviceTypesReadDeviceTypeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/device-types/{device_type_id}',
            path: {
                device_type_id: data.deviceTypeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Device Type
     * Update a device type.
     * @param data The data for the request.
     * @param data.deviceTypeId
     * @param data.requestBody
     * @returns DeviceTypePublic Successful Response
     * @throws ApiError
     */
    public static updateDeviceType(data: DeviceTypesUpdateDeviceTypeData): CancelablePromise<DeviceTypesUpdateDeviceTypeResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/device-types/{device_type_id}',
            path: {
                device_type_id: data.deviceTypeId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Device Type
     * Delete a device type.
     * @param data The data for the request.
     * @param data.deviceTypeId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteDeviceType(data: DeviceTypesDeleteDeviceTypeData): CancelablePromise<DeviceTypesDeleteDeviceTypeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/device-types/{device_type_id}',
            path: {
                device_type_id: data.deviceTypeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ImmichSyncJobsService {
    /**
     * Read Sync Jobs
     * Retrieve Immich sync jobs with pagination.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * skip: Number of records to skip
     * limit: Maximum number of records to return
     *
     * Returns:
     * Paginated list of sync jobs
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ImmichSyncJobsPublic Successful Response
     * @throws ApiError
     */
    public static readSyncJobs(data: ImmichSyncJobsReadSyncJobsData = {}): CancelablePromise<ImmichSyncJobsReadSyncJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/immich-sync-jobs/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Sync Job
     * Create new Immich sync job.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * job_in: Sync job creation data
     *
     * Returns:
     * Created sync job record
     *
     * Raises:
     * HTTPException: If validation fails (duplicate name, device not found, etc.)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ImmichSyncJobPublic Successful Response
     * @throws ApiError
     */
    public static createSyncJob(data: ImmichSyncJobsCreateSyncJobData): CancelablePromise<ImmichSyncJobsCreateSyncJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/immich-sync-jobs/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Sync Job
     * Get sync job by ID.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * job_id: Sync job UUID
     *
     * Returns:
     * Sync job record
     *
     * Raises:
     * HTTPException: If sync job not found
     * @param data The data for the request.
     * @param data.jobId
     * @returns ImmichSyncJobPublic Successful Response
     * @throws ApiError
     */
    public static readSyncJob(data: ImmichSyncJobsReadSyncJobData): CancelablePromise<ImmichSyncJobsReadSyncJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/immich-sync-jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Sync Job
     * Update an Immich sync job.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * job_id: Sync job UUID
     * job_in: Updated sync job data
     *
     * Returns:
     * Updated sync job record
     *
     * Raises:
     * HTTPException: If sync job not found or validation fails
     * @param data The data for the request.
     * @param data.jobId
     * @param data.requestBody
     * @returns ImmichSyncJobPublic Successful Response
     * @throws ApiError
     */
    public static updateSyncJob(data: ImmichSyncJobsUpdateSyncJobData): CancelablePromise<ImmichSyncJobsUpdateSyncJobResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/immich-sync-jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Sync Job
     * Delete an Immich sync job.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * job_id: Sync job UUID
     *
     * Returns:
     * Success message
     *
     * Raises:
     * HTTPException: If sync job not found
     * @param data The data for the request.
     * @param data.jobId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteSyncJob(data: ImmichSyncJobsDeleteSyncJobData): CancelablePromise<ImmichSyncJobsDeleteSyncJobResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/immich-sync-jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class InfrastructureService {
    /**
     * Health
     * Health check endpoint.
     *
     * Returns a simple status response to indicate the service is running.
     *
     * Returns:
     * HealthResponse: Current health status.
     * @returns HealthResponse Successful Response
     * @throws ApiError
     */
    public static health(): CancelablePromise<InfrastructureHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
}

export class MonitoringService {
    /**
     * Read Skills
     * List all registered skills.
     * @returns SkillsPublic Successful Response
     * @throws ApiError
     */
    public static readSkills(): CancelablePromise<MonitoringReadSkillsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/monitoring/skills'
        });
    }
}

export class PictureDisplayService {
    /**
     * Upload Image
     * Upload image to MinIO and create database record.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * file: Image file to upload
     * title: Optional image title
     * description: Optional image description
     * tags: Optional comma-separated tags
     * display_duration_seconds: Display duration (default 3600 seconds)
     * priority: Display priority (default 0)
     *
     * Returns:
     * Created image record
     *
     * Raises:
     * HTTPException: If file validation fails or upload fails
     * @param data The data for the request.
     * @param data.formData
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static uploadImage(data: PictureDisplayUploadImageData): CancelablePromise<PictureDisplayUploadImageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/picture-display/images/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Images
     * Retrieve images with pagination.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * skip: Number of records to skip
     * limit: Maximum number of records to return
     *
     * Returns:
     * Paginated list of images
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ImagesPublic Successful Response
     * @throws ApiError
     */
    public static readImages(data: PictureDisplayReadImagesData = {}): CancelablePromise<PictureDisplayReadImagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/picture-display/images/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Image
     * Get image by ID.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * image_id: Image UUID
     *
     * Returns:
     * Image record
     *
     * Raises:
     * HTTPException: If image not found
     * @param data The data for the request.
     * @param data.imageId
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static readImage(data: PictureDisplayReadImageData): CancelablePromise<PictureDisplayReadImageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/picture-display/images/{image_id}',
            path: {
                image_id: data.imageId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Image
     * Update image metadata.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * image_id: Image UUID
     * image_in: Updated image metadata
     *
     * Returns:
     * Updated image record
     *
     * Raises:
     * HTTPException: If image not found
     * @param data The data for the request.
     * @param data.imageId
     * @param data.requestBody
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static updateImage(data: PictureDisplayUpdateImageData): CancelablePromise<PictureDisplayUpdateImageResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/picture-display/images/{image_id}',
            path: {
                image_id: data.imageId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Image
     * Delete image from MinIO and database.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * image_id: Image UUID
     *
     * Returns:
     * Success message
     *
     * Raises:
     * HTTPException: If image not found
     * @param data The data for the request.
     * @param data.imageId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteImage(data: PictureDisplayDeleteImageData): CancelablePromise<PictureDisplayDeleteImageResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/picture-display/images/{image_id}',
            path: {
                image_id: data.imageId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Image Url
     * Get presigned URL for image access.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * image_id: Image UUID
     * expires_hours: URL expiration time in hours (default: 1)
     *
     * Returns:
     * Presigned URL and expiration time
     *
     * Raises:
     * HTTPException: If image not found or URL generation fails
     * @param data The data for the request.
     * @param data.imageId
     * @param data.expiresHours
     * @returns PresignedUrlResponse Successful Response
     * @throws ApiError
     */
    public static getImageUrl(data: PictureDisplayGetImageUrlData): CancelablePromise<PictureDisplayGetImageUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/picture-display/images/{image_id}/url',
            path: {
                image_id: data.imageId
            },
            query: {
                expires_hours: data.expiresHours
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RoomsService {
    /**
     * Read Rooms
     * Retrieve rooms with pagination.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns RoomsPublic Successful Response
     * @throws ApiError
     */
    public static readRooms(data: RoomsReadRoomsData = {}): CancelablePromise<RoomsReadRoomsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rooms/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Room
     * Create new room.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RoomPublic Successful Response
     * @throws ApiError
     */
    public static createRoom(data: RoomsCreateRoomData): CancelablePromise<RoomsCreateRoomResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rooms/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Room
     * Get room by ID.
     * @param data The data for the request.
     * @param data.roomId
     * @returns RoomPublic Successful Response
     * @throws ApiError
     */
    public static readRoom(data: RoomsReadRoomData): CancelablePromise<RoomsReadRoomResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rooms/{room_id}',
            path: {
                room_id: data.roomId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Room
     * Update a room.
     * @param data The data for the request.
     * @param data.roomId
     * @param data.requestBody
     * @returns RoomPublic Successful Response
     * @throws ApiError
     */
    public static updateRoom(data: RoomsUpdateRoomData): CancelablePromise<RoomsUpdateRoomResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/rooms/{room_id}',
            path: {
                room_id: data.roomId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Room
     * Delete a room.
     * @param data The data for the request.
     * @param data.roomId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteRoom(data: RoomsDeleteRoomData): CancelablePromise<RoomsDeleteRoomResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rooms/{room_id}',
            path: {
                room_id: data.roomId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}