// This file is auto-generated by @hey-api/openapi-ts

/**
 * Public schema for IntentPattern in monitoring context.
 */
export type app__api__routes__monitoring__IntentPatternPublic = {
    id: string;
    intent_type: string;
    description?: (string | null);
    priority: number;
    enabled: boolean;
};

/**
 * Public API model for IntentPattern with nested keywords.
 */
export type app__models_commons_api__IntentPatternPublic = {
    intent_type: string;
    enabled?: boolean;
    priority?: number;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    keywords: Array<IntentPatternKeywordPublic>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_picture_display_upload_image = {
    file: (Blob | File);
    title?: (string | null);
    description?: (string | null);
    tags?: (string | null);
    display_duration_seconds?: number;
    priority?: number;
};

/**
 * Model for creating a new device type.
 */
export type DeviceTypeCreate = {
    name: string;
};

/**
 * Public API model for DeviceType.
 */
export type DeviceTypePublic = {
    name: string;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for device types.
 */
export type DeviceTypesPublic = {
    data: Array<DeviceTypePublic>;
    count: number;
};

/**
 * Model for updating a device type.
 */
export type DeviceTypeUpdate = {
    name?: (string | null);
};

/**
 * Model for creating a new global device.
 */
export type GlobalDeviceCreate = {
    name: string;
    device_type_id: string;
    room_id?: (string | null);
    skill_id: string;
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Public API model for GlobalDevice.
 */
export type GlobalDevicePublic = {
    name: string;
    device_type_id: string;
    room_id?: (string | null);
    skill_id: string;
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for global devices.
 */
export type GlobalDevicesPublic = {
    data: Array<GlobalDevicePublic>;
    count: number;
};

/**
 * Model for updating a global device.
 */
export type GlobalDeviceUpdate = {
    name?: (string | null);
    device_type_id?: (string | null);
    room_id?: (string | null);
    skill_id?: (string | null);
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Health check response model.
 *
 * Attributes:
 * status: Current health status of the application.
 */
export type HealthResponse = {
    /**
     * Health status of the application
     */
    status?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Image metadata stored in the database.
 *
 * Images are fetched from various sources (manual upload, Immich, Unsplash, etc.)
 * and stored in MinIO. This table tracks metadata for display scheduling and
 * voice command responses.
 *
 * Attributes:
 * id: Unique identifier for the image
 * source_name: Source identifier (e.g., "manual", "immich", "unsplash")
 * storage_path: Path to image in MinIO bucket
 * title: Optional title for voice responses
 * description: Optional description for "what am I seeing?" queries
 * author: Optional author/photographer name
 * source_url: Optional URL to original source
 * display_duration_seconds: How long to show this image (default 3600)
 * priority: Weight for future priority-based selection (default 0)
 * original_width: Image width in pixels
 * original_height: Image height in pixels
 * last_displayed_at: When the image was last shown (for FIFO selection)
 * expires_at: Optional expiration time for auto-cleanup
 * created_at: When record was created (replaces fetched_at)
 * updated_at: When record was last updated
 * tags: Comma-separated tags for categorization
 */
export type Image = {
    id?: string;
    /**
     * Source identifier (e.g. manual, unsplash)
     */
    source_name: string;
    /**
     * MinIO object path
     */
    storage_path: string;
    /**
     * Image title for voice responses
     */
    title?: (string | null);
    /**
     * Description for 'what am I seeing?'
     */
    description?: (string | null);
    /**
     * Author/photographer name
     */
    author?: (string | null);
    /**
     * Original source URL
     */
    source_url?: (string | null);
    /**
     * Display duration in seconds
     */
    display_duration_seconds?: number;
    /**
     * Priority weight for selection (higher = more likely)
     */
    priority?: number;
    /**
     * Image width in pixels
     */
    original_width?: (number | null);
    /**
     * Image height in pixels
     */
    original_height?: (number | null);
    /**
     * Last display time for FIFO
     */
    last_displayed_at?: (string | null);
    /**
     * Expiration time for cleanup
     */
    expires_at?: (string | null);
    /**
     * When record was created
     */
    created_at?: string;
    /**
     * When record was last updated
     */
    updated_at?: string;
    /**
     * Comma-separated tags for categorization
     */
    tags?: (string | null);
};

/**
 * API response model for Image.
 */
export type ImagePublic = {
    id: string;
    source_name: string;
    storage_path: string;
    title: (string | null);
    description: (string | null);
    author: (string | null);
    source_url: (string | null);
    tags: (string | null);
    display_duration_seconds: number;
    priority: number;
    original_width: (number | null);
    original_height: (number | null);
    last_displayed_at: (string | null);
    expires_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for images.
 */
export type ImagesPublic = {
    data: Array<ImagePublic>;
    count: number;
};

/**
 * API request model for updating images.
 */
export type ImageUpdate = {
    title?: (string | null);
    description?: (string | null);
    tags?: (string | null);
    display_duration_seconds?: (number | null);
    priority?: (number | null);
};

/**
 * API request model for creating sync jobs.
 */
export type ImmichSyncJobCreate = {
    /**
     * Unique job name
     */
    name: string;
    /**
     * Device this job syncs for
     */
    target_device_id: string;
    /**
     * Selection strategy: RANDOM or SMART
     */
    strategy?: SyncStrategy;
    /**
     * Semantic search query for SMART strategy
     */
    query?: (string | null);
    /**
     * Images to sync per run
     */
    count?: number;
    /**
     * Randomly sample from smart search results
     */
    random_pick?: boolean;
    /**
     * Multiplier for overfetching when client-side filters active
     */
    overfetch_multiplier?: number;
    /**
     * Minimum color compatibility score (0 to disable)
     */
    min_color_score?: number;
    /**
     * Whether job is active
     */
    is_active?: boolean;
    /**
     * Filter by album UUIDs
     */
    album_ids?: (Array<(string)> | null);
    /**
     * Filter by person UUIDs
     */
    person_ids?: (Array<(string)> | null);
    /**
     * Filter by tag UUIDs
     */
    tag_ids?: (Array<(string)> | null);
    /**
     * Filter favorites only
     */
    is_favorite?: (boolean | null);
    /**
     * Filter by city
     */
    city?: (string | null);
    /**
     * Filter by state/region
     */
    state?: (string | null);
    /**
     * Filter by country
     */
    country?: (string | null);
    /**
     * Photos taken after this date
     */
    taken_after?: (string | null);
    /**
     * Photos taken before this date
     */
    taken_before?: (string | null);
    /**
     * Minimum rating (0-5)
     */
    rating?: (number | null);
};

/**
 * API response model for sync jobs.
 */
export type ImmichSyncJobPublic = {
    /**
     * Unique job name
     */
    name: string;
    /**
     * Device this job syncs for
     */
    target_device_id: string;
    /**
     * Selection strategy: RANDOM or SMART
     */
    strategy?: SyncStrategy;
    /**
     * Semantic search query for SMART strategy
     */
    query?: (string | null);
    /**
     * Images to sync per run
     */
    count?: number;
    /**
     * Randomly sample from smart search results
     */
    random_pick?: boolean;
    /**
     * Multiplier for overfetching when client-side filters active
     */
    overfetch_multiplier?: number;
    /**
     * Minimum color compatibility score (0 to disable)
     */
    min_color_score?: number;
    /**
     * Whether job is active
     */
    is_active?: boolean;
    /**
     * Filter by album UUIDs
     */
    album_ids?: (Array<(string)> | null);
    /**
     * Filter by person UUIDs
     */
    person_ids?: (Array<(string)> | null);
    /**
     * Filter by tag UUIDs
     */
    tag_ids?: (Array<(string)> | null);
    /**
     * Filter favorites only
     */
    is_favorite?: (boolean | null);
    /**
     * Filter by city
     */
    city?: (string | null);
    /**
     * Filter by state/region
     */
    state?: (string | null);
    /**
     * Filter by country
     */
    country?: (string | null);
    /**
     * Photos taken after this date
     */
    taken_after?: (string | null);
    /**
     * Photos taken before this date
     */
    taken_before?: (string | null);
    /**
     * Minimum rating (0-5)
     */
    rating?: (number | null);
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for sync jobs.
 */
export type ImmichSyncJobsPublic = {
    data: Array<ImmichSyncJobPublic>;
    count: number;
};

/**
 * API request model for updating sync jobs.
 *
 * All fields are optional to allow partial updates.
 */
export type ImmichSyncJobUpdate = {
    name?: (string | null);
    target_device_id?: (string | null);
    strategy?: (SyncStrategy | null);
    query?: (string | null);
    count?: (number | null);
    random_pick?: (boolean | null);
    overfetch_multiplier?: (number | null);
    min_color_score?: (number | null);
    is_active?: (boolean | null);
    album_ids?: (Array<(string)> | null);
    person_ids?: (Array<(string)> | null);
    tag_ids?: (Array<(string)> | null);
    is_favorite?: (boolean | null);
    city?: (string | null);
    state?: (string | null);
    country?: (string | null);
    taken_after?: (string | null);
    taken_before?: (string | null);
    rating?: (number | null);
};

/**
 * Model for creating a new intent pattern with keywords.
 */
export type IntentPatternCreate = {
    intent_type: string;
    enabled?: boolean;
    priority?: number;
    description?: (string | null);
    keywords?: Array<IntentPatternKeywordCreate>;
};

/**
 * Model for creating a new keyword (nested in IntentPattern).
 */
export type IntentPatternKeywordCreate = {
    keyword: string;
    keyword_type?: string;
    is_regex?: boolean;
    weight?: number;
};

/**
 * Public API model for IntentPatternKeyword.
 */
export type IntentPatternKeywordPublic = {
    keyword: string;
    keyword_type?: string;
    is_regex?: boolean;
    weight?: number;
    id: string;
    pattern_id: string;
    created_at: string;
};

/**
 * Paginated response for intent patterns.
 */
export type IntentPatternsPublic = {
    data: Array<app__models_commons_api__IntentPatternPublic>;
    count: number;
};

/**
 * Model for updating an intent pattern.
 */
export type IntentPatternUpdate = {
    intent_type?: (string | null);
    enabled?: (boolean | null);
    priority?: (number | null);
    description?: (string | null);
    keywords?: (Array<IntentPatternKeywordCreate> | null);
};

export type Message = {
    message: string;
};

/**
 * Response model for presigned URL.
 */
export type PresignedUrlResponse = {
    url: string;
    expires_in_seconds: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Model for creating a new room.
 */
export type RoomCreate = {
    name: string;
};

/**
 * Public API model for Room.
 */
export type RoomPublic = {
    name: string;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for rooms.
 */
export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

/**
 * Model for updating a room.
 */
export type RoomUpdate = {
    name?: (string | null);
};

/**
 * Public API model for SkillIntent.
 */
export type SkillIntentPublic = {
    skill_id: string;
    intent_pattern_id: string;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for skill-intents.
 */
export type SkillIntentsPublic = {
    data: Array<SkillIntentPublic>;
    count: number;
};

/**
 * Public schema for Skill with supported intent patterns.
 */
export type SkillPublic = {
    id: string;
    name: string;
    help_text?: (string | null);
    created_at: string;
    updated_at: string;
    intent_patterns?: Array<app__api__routes__monitoring__IntentPatternPublic>;
};

/**
 * Paginated response for skills.
 */
export type SkillsPublic = {
    data: Array<SkillPublic>;
    count: number;
};

/**
 * Strategy for selecting images from Immich.
 *
 * Values are uppercase to match PostgreSQL enum labels created by SQLAlchemy.
 */
export type SyncStrategy = 'RANDOM' | 'SMART';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DevicesReadDevicesData = {
    limit?: number;
    skip?: number;
};

export type DevicesReadDevicesResponse = (GlobalDevicesPublic);

export type DevicesCreateDeviceData = {
    requestBody: GlobalDeviceCreate;
};

export type DevicesCreateDeviceResponse = (GlobalDevicePublic);

export type DevicesReadDeviceData = {
    deviceId: string;
};

export type DevicesReadDeviceResponse = (GlobalDevicePublic);

export type DevicesUpdateDeviceData = {
    deviceId: string;
    requestBody: GlobalDeviceUpdate;
};

export type DevicesUpdateDeviceResponse = (GlobalDevicePublic);

export type DevicesDeleteDeviceData = {
    deviceId: string;
};

export type DevicesDeleteDeviceResponse = (Message);

export type DeviceTypesReadDeviceTypesData = {
    limit?: number;
    skip?: number;
};

export type DeviceTypesReadDeviceTypesResponse = (DeviceTypesPublic);

export type DeviceTypesCreateDeviceTypeData = {
    requestBody: DeviceTypeCreate;
};

export type DeviceTypesCreateDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesReadDeviceTypeData = {
    deviceTypeId: string;
};

export type DeviceTypesReadDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesUpdateDeviceTypeData = {
    deviceTypeId: string;
    requestBody: DeviceTypeUpdate;
};

export type DeviceTypesUpdateDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesDeleteDeviceTypeData = {
    deviceTypeId: string;
};

export type DeviceTypesDeleteDeviceTypeResponse = (Message);

export type ImmichSyncJobsReadSyncJobsData = {
    limit?: number;
    skip?: number;
};

export type ImmichSyncJobsReadSyncJobsResponse = (ImmichSyncJobsPublic);

export type ImmichSyncJobsCreateSyncJobData = {
    requestBody: ImmichSyncJobCreate;
};

export type ImmichSyncJobsCreateSyncJobResponse = (ImmichSyncJobPublic);

export type ImmichSyncJobsReadSyncJobData = {
    jobId: string;
};

export type ImmichSyncJobsReadSyncJobResponse = (ImmichSyncJobPublic);

export type ImmichSyncJobsUpdateSyncJobData = {
    jobId: string;
    requestBody: ImmichSyncJobUpdate;
};

export type ImmichSyncJobsUpdateSyncJobResponse = (ImmichSyncJobPublic);

export type ImmichSyncJobsDeleteSyncJobData = {
    jobId: string;
};

export type ImmichSyncJobsDeleteSyncJobResponse = (Message);

export type InfrastructureHealthResponse = (HealthResponse);

export type IntentPatternsReadIntentPatternsData = {
    limit?: number;
    skip?: number;
};

export type IntentPatternsReadIntentPatternsResponse = (IntentPatternsPublic);

export type IntentPatternsCreateIntentPatternData = {
    requestBody: IntentPatternCreate;
};

export type IntentPatternsCreateIntentPatternResponse = (app__models_commons_api__IntentPatternPublic);

export type IntentPatternsReadIntentPatternData = {
    patternId: string;
};

export type IntentPatternsReadIntentPatternResponse = (app__models_commons_api__IntentPatternPublic);

export type IntentPatternsUpdateIntentPatternData = {
    patternId: string;
    requestBody: IntentPatternUpdate;
};

export type IntentPatternsUpdateIntentPatternResponse = (app__models_commons_api__IntentPatternPublic);

export type IntentPatternsDeleteIntentPatternData = {
    patternId: string;
};

export type IntentPatternsDeleteIntentPatternResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type MonitoringReadSkillsResponse = (SkillsPublic);

export type PictureDisplayUploadImageData = {
    formData: Body_picture_display_upload_image;
};

export type PictureDisplayUploadImageResponse = (Image);

export type PictureDisplayReadImagesData = {
    limit?: number;
    skip?: number;
};

export type PictureDisplayReadImagesResponse = (ImagesPublic);

export type PictureDisplayReadImageData = {
    imageId: string;
};

export type PictureDisplayReadImageResponse = (ImagePublic);

export type PictureDisplayUpdateImageData = {
    imageId: string;
    requestBody: ImageUpdate;
};

export type PictureDisplayUpdateImageResponse = (ImagePublic);

export type PictureDisplayDeleteImageData = {
    imageId: string;
};

export type PictureDisplayDeleteImageResponse = (Message);

export type PictureDisplayGetImageUrlData = {
    expiresHours?: number;
    imageId: string;
};

export type PictureDisplayGetImageUrlResponse = (PresignedUrlResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RoomsReadRoomsData = {
    limit?: number;
    skip?: number;
};

export type RoomsReadRoomsResponse = (RoomsPublic);

export type RoomsCreateRoomData = {
    requestBody: RoomCreate;
};

export type RoomsCreateRoomResponse = (RoomPublic);

export type RoomsReadRoomData = {
    roomId: string;
};

export type RoomsReadRoomResponse = (RoomPublic);

export type RoomsUpdateRoomData = {
    requestBody: RoomUpdate;
    roomId: string;
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsDeleteRoomData = {
    roomId: string;
};

export type RoomsDeleteRoomResponse = (Message);

export type SkillIntentsReadSkillIntentsData = {
    limit?: number;
    skillId?: (string | null);
    skip?: number;
};

export type SkillIntentsReadSkillIntentsResponse = (SkillIntentsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);