// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_picture_display_upload_image = {
    file: (Blob | File);
    title?: (string | null);
    description?: (string | null);
    tags?: (string | null);
    display_duration_seconds?: number;
    priority?: number;
};

/**
 * Model for creating a new device type.
 */
export type DeviceTypeCreate = {
    name: string;
};

/**
 * Public API model for DeviceType.
 */
export type DeviceTypePublic = {
    name: string;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for device types.
 */
export type DeviceTypesPublic = {
    data: Array<DeviceTypePublic>;
    count: number;
};

/**
 * Model for updating a device type.
 */
export type DeviceTypeUpdate = {
    name?: (string | null);
};

/**
 * Model for creating a new global device.
 */
export type GlobalDeviceCreate = {
    name: string;
    device_type_id: string;
    room_id?: (string | null);
    skill_id: string;
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Public API model for GlobalDevice.
 */
export type GlobalDevicePublic = {
    name: string;
    device_type_id: string;
    room_id?: (string | null);
    skill_id: string;
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for global devices.
 */
export type GlobalDevicesPublic = {
    data: Array<GlobalDevicePublic>;
    count: number;
};

/**
 * Model for updating a global device.
 */
export type GlobalDeviceUpdate = {
    name?: (string | null);
    device_type_id?: (string | null);
    room_id?: (string | null);
    skill_id?: (string | null);
    pattern?: (Array<(string)> | null);
    device_attributes?: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

/**
 * Public API model for images.
 */
export type PictureDisplayImagePublic = {
    id: string;
    source_name: string;
    storage_path: string;
    title: (string | null);
    description: (string | null);
    tags: (string | null);
    display_duration_seconds: number;
    priority: number;
    last_displayed_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for images.
 */
export type PictureDisplayImagesPublic = {
    data: Array<PictureDisplayImagePublic>;
    count: number;
};

/**
 * Model for updating images.
 */
export type PictureDisplayImageUpdate = {
    title?: (string | null);
    description?: (string | null);
    tags?: (string | null);
    display_duration_seconds?: (number | null);
    priority?: (number | null);
};

/**
 * Response model for presigned URL.
 */
export type PresignedUrlResponse = {
    url: string;
    expires_in_seconds: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Model for creating a new room.
 */
export type RoomCreate = {
    name: string;
};

/**
 * Public API model for Room.
 */
export type RoomPublic = {
    name: string;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for rooms.
 */
export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

/**
 * Model for updating a room.
 */
export type RoomUpdate = {
    name?: (string | null);
};

/**
 * Public schema for Skill.
 */
export type SkillPublic = {
    id: string;
    name: string;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated response for skills.
 */
export type SkillsPublic = {
    data: Array<SkillPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DevicesReadDevicesData = {
    limit?: number;
    skip?: number;
};

export type DevicesReadDevicesResponse = (GlobalDevicesPublic);

export type DevicesCreateDeviceData = {
    requestBody: GlobalDeviceCreate;
};

export type DevicesCreateDeviceResponse = (GlobalDevicePublic);

export type DevicesReadDeviceData = {
    deviceId: string;
};

export type DevicesReadDeviceResponse = (GlobalDevicePublic);

export type DevicesUpdateDeviceData = {
    deviceId: string;
    requestBody: GlobalDeviceUpdate;
};

export type DevicesUpdateDeviceResponse = (GlobalDevicePublic);

export type DevicesDeleteDeviceData = {
    deviceId: string;
};

export type DevicesDeleteDeviceResponse = (Message);

export type DeviceTypesReadDeviceTypesData = {
    limit?: number;
    skip?: number;
};

export type DeviceTypesReadDeviceTypesResponse = (DeviceTypesPublic);

export type DeviceTypesCreateDeviceTypeData = {
    requestBody: DeviceTypeCreate;
};

export type DeviceTypesCreateDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesReadDeviceTypeData = {
    deviceTypeId: string;
};

export type DeviceTypesReadDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesUpdateDeviceTypeData = {
    deviceTypeId: string;
    requestBody: DeviceTypeUpdate;
};

export type DeviceTypesUpdateDeviceTypeResponse = (DeviceTypePublic);

export type DeviceTypesDeleteDeviceTypeData = {
    deviceTypeId: string;
};

export type DeviceTypesDeleteDeviceTypeResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type MonitoringReadSkillsResponse = (SkillsPublic);

export type PictureDisplayUploadImageData = {
    formData: Body_picture_display_upload_image;
};

export type PictureDisplayUploadImageResponse = (PictureDisplayImagePublic);

export type PictureDisplayReadImagesData = {
    limit?: number;
    skip?: number;
};

export type PictureDisplayReadImagesResponse = (PictureDisplayImagesPublic);

export type PictureDisplayReadImageData = {
    imageId: string;
};

export type PictureDisplayReadImageResponse = (PictureDisplayImagePublic);

export type PictureDisplayUpdateImageData = {
    imageId: string;
    requestBody: PictureDisplayImageUpdate;
};

export type PictureDisplayUpdateImageResponse = (PictureDisplayImagePublic);

export type PictureDisplayDeleteImageData = {
    imageId: string;
};

export type PictureDisplayDeleteImageResponse = (Message);

export type PictureDisplayGetImageUrlData = {
    expiresHours?: number;
    imageId: string;
};

export type PictureDisplayGetImageUrlResponse = (PresignedUrlResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RoomsReadRoomsData = {
    limit?: number;
    skip?: number;
};

export type RoomsReadRoomsResponse = (RoomsPublic);

export type RoomsCreateRoomData = {
    requestBody: RoomCreate;
};

export type RoomsCreateRoomResponse = (RoomPublic);

export type RoomsReadRoomData = {
    roomId: string;
};

export type RoomsReadRoomResponse = (RoomPublic);

export type RoomsUpdateRoomData = {
    requestBody: RoomUpdate;
    roomId: string;
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsDeleteRoomData = {
    roomId: string;
};

export type RoomsDeleteRoomResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);