/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRoomsRouteImport } from './routes/_layout/rooms'
import { Route as LayoutPictureDisplayRouteImport } from './routes/_layout/picture-display'
import { Route as LayoutMonitoringRouteImport } from './routes/_layout/monitoring'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/devices'
import { Route as LayoutDeviceTypesRouteImport } from './routes/_layout/device-types'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsRoute = LayoutRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPictureDisplayRoute = LayoutPictureDisplayRouteImport.update({
  id: '/picture-display',
  path: '/picture-display',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMonitoringRoute = LayoutMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeviceTypesRoute = LayoutDeviceTypesRouteImport.update({
  id: '/device-types',
  path: '/device-types',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/device-types': typeof LayoutDeviceTypesRoute
  '/devices': typeof LayoutDevicesRoute
  '/monitoring': typeof LayoutMonitoringRoute
  '/picture-display': typeof LayoutPictureDisplayRoute
  '/rooms': typeof LayoutRoomsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/device-types': typeof LayoutDeviceTypesRoute
  '/devices': typeof LayoutDevicesRoute
  '/monitoring': typeof LayoutMonitoringRoute
  '/picture-display': typeof LayoutPictureDisplayRoute
  '/rooms': typeof LayoutRoomsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/device-types': typeof LayoutDeviceTypesRoute
  '/_layout/devices': typeof LayoutDevicesRoute
  '/_layout/monitoring': typeof LayoutMonitoringRoute
  '/_layout/picture-display': typeof LayoutPictureDisplayRoute
  '/_layout/rooms': typeof LayoutRoomsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/oauth-callback'
    | '/admin'
    | '/device-types'
    | '/devices'
    | '/monitoring'
    | '/picture-display'
    | '/rooms'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/oauth-callback'
    | '/admin'
    | '/device-types'
    | '/devices'
    | '/monitoring'
    | '/picture-display'
    | '/rooms'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/oauth-callback'
    | '/_layout/admin'
    | '/_layout/device-types'
    | '/_layout/devices'
    | '/_layout/monitoring'
    | '/_layout/picture-display'
    | '/_layout/rooms'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms': {
      id: '/_layout/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof LayoutRoomsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/picture-display': {
      id: '/_layout/picture-display'
      path: '/picture-display'
      fullPath: '/picture-display'
      preLoaderRoute: typeof LayoutPictureDisplayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/monitoring': {
      id: '/_layout/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof LayoutMonitoringRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices': {
      id: '/_layout/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/device-types': {
      id: '/_layout/device-types'
      path: '/device-types'
      fullPath: '/device-types'
      preLoaderRoute: typeof LayoutDeviceTypesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDeviceTypesRoute: typeof LayoutDeviceTypesRoute
  LayoutDevicesRoute: typeof LayoutDevicesRoute
  LayoutMonitoringRoute: typeof LayoutMonitoringRoute
  LayoutPictureDisplayRoute: typeof LayoutPictureDisplayRoute
  LayoutRoomsRoute: typeof LayoutRoomsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDeviceTypesRoute: LayoutDeviceTypesRoute,
  LayoutDevicesRoute: LayoutDevicesRoute,
  LayoutMonitoringRoute: LayoutMonitoringRoute,
  LayoutPictureDisplayRoute: LayoutPictureDisplayRoute,
  LayoutRoomsRoute: LayoutRoomsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
